"""
Document Chat Service
Orchestrates MongoDB + Postgres + LLM for the workspace chat feature.
Implements LLM context routing: resolves which document tab is active,
fetches its live content, and injects it into the LLM system prompt.
"""

import json
from typing import Any, Dict, List, Optional
from uuid import UUID

from motor.motor_asyncio import AsyncIOMotorDatabase
from sqlalchemy.ext.asyncio import AsyncSession

from app.repositories.chat_session_repository import chat_session_repo
from app.repositories.group_document_repository import group_document_repo
from app.services.llm import call_llm


class DocumentChatService:

    # ── Workspace (Session) Management ──────────────────────────────────────

    async def create_workspace(
        self,
        db: AsyncIOMotorDatabase,
        session_id: str,
        group_id: str,
        title: str,
        created_by: str,
        document_ids: Optional[List[str]] = None,
    ) -> Dict[str, Any]:
        """
        Create a new MongoDB workspace session.
        The session_id is pre-generated by the caller so it can also be
        stored on group_documents.chat_session_id in Postgres.
        """
        return await chat_session_repo.create_session(
            db,
            session_id=session_id,
            group_id=group_id,
            title=title,
            created_by=created_by,
            document_ids=document_ids or [],
        )

    async def get_workspace(
        self, db: AsyncIOMotorDatabase, session_id: str
    ) -> Optional[Dict[str, Any]]:
        return await chat_session_repo.get_session(db, session_id)

    async def list_workspaces(
        self,
        db: AsyncIOMotorDatabase,
        group_id: str,
        active_only: bool = True,
    ) -> List[Dict[str, Any]]:
        return await chat_session_repo.list_sessions_for_group(
            db, group_id, active_only=active_only
        )

    async def link_document_to_session(
        self,
        db: AsyncIOMotorDatabase,
        session_id: str,
        document_id: str,
    ) -> None:
        """
        Append a Postgres document UUID to the workspace's document_ids array.
        Idempotent — $addToSet ignores duplicates.
        """
        await chat_session_repo.add_document_to_session(db, session_id, document_id)

    async def rename_workspace(
        self, db: AsyncIOMotorDatabase, session_id: str, title: str
    ) -> bool:
        return await chat_session_repo.rename_session(db, session_id, title)

    async def delete_workspace(self, db: AsyncIOMotorDatabase, session_id: str) -> bool:
        return await chat_session_repo.delete_session(db, session_id)

    # ── Message + LLM ───────────────────────────────────────────────────────

    async def get_messages(
        self,
        mongo_db: AsyncIOMotorDatabase,
        chat_session_id: str,
        skip: int = 0,
        limit: int = 50,
    ) -> List[Dict[str, Any]]:
        return await chat_session_repo.get_messages(
            mongo_db, chat_session_id, skip=skip, limit=limit
        )

    async def send_message_with_llm(
        self,
        pg_db: AsyncSession,
        mongo_db: AsyncIOMotorDatabase,
        chat_session_id: str,
        sender_id: str,
        content: str,
        active_document_id: Optional[str],
        model_choice: str = "gpt-4o",
    ) -> str:
        """
        Full message round-trip:
        1. Persist the student's message to MongoDB.
        2. Resolve the active document's live content from Postgres.
        3. Build LLM history from the last 10 messages.
        4. Call GitHub Models with document context injected into system prompt.
        5. Persist the LLM reply to MongoDB.
        6. Return the reply text.
        """
        # Build doc_context payload for the student message
        doc_context: Optional[Dict[str, Any]] = None
        document_content_str: Optional[str] = None
        doc_type_str: Optional[str] = None

        if active_document_id:
            doc = await group_document_repo.get_by_id(pg_db, UUID(active_document_id))
            if doc:
                if doc.doc_type:
                    doc_type_str = doc.doc_type.value

                if doc.content:
                    document_content_str = json.dumps(doc.content, indent=2)
                    doc_context = {
                        "active_document_id": active_document_id,
                        "version_number": doc.lock_version,
                    }

        # 1. Save the student's message
        await chat_session_repo.save_message(
            mongo_db,
            chat_session_id=chat_session_id,
            sender_id=sender_id,
            sender_type="student",
            content=content,
            doc_context=doc_context,
        )

        # 2. Fetch recent history for LLM context
        recent = await chat_session_repo.get_recent_messages_for_context(
            mongo_db, chat_session_id, n=10
        )

        # 3. Shape history into OpenAI message format
        history: List[Dict[str, str]] = []
        for msg in recent:
            role = "assistant" if msg["sender_type"] == "llm" else "user"
            history.append({"role": role, "content": msg["content"]})

        # 4. Call LLM
        try:
            reply = await call_llm(
                history=history,
                document_content=document_content_str,
                model_choice=model_choice,
                doc_type=doc_type_str,
            )
        except Exception as exc:
            reply = f"[AI Error] {exc}"

        # 5. Persist LLM reply
        await chat_session_repo.save_message(
            mongo_db,
            chat_session_id=chat_session_id,
            sender_id="llm",
            sender_type="llm",
            content=reply,
            doc_context=doc_context,
        )

        return reply


document_chat_service = DocumentChatService()
